### ISSUE TITLE
 Property hourly_rate_after_date must be a list

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#256]
http://rebuildingtogethercaptain.appspot.com/room/stafftime/new/5772013629079552/

Original Traceback (most recent call last):
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/template/debug.py", line 71, in render_node
    result = node.render(context)
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/template/debug.py", line 87, in render
    output = force_unicode(self.filter_expression.resolve(context))
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/utils/encoding.py", line 49, in force_unicode
    s = unicode(s)
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/forms/forms.py", line 94, in __unicode__
    return self.as_table()
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/forms/forms.py", line 190, in as_table
    return self._html_output(u'<tr><th>%(label)s</th><td>%(errors)s%(field)s%(help_text)s</td></tr>', u'<tr><td colspan="2">%s</td></tr>', '</td></tr>', u'<br />%s', False)
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/forms/forms.py", line 165, in _html_output
    output.append(normal_row % {'errors': force_unicode(bf_errors), 'label': force_unicode(label), 'field': unicode(bf), 'help_text': help_text})
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/forms/forms.py", line 333, in __unicode__
    return self.as_widget()
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/forms/forms.py", line 365, in as_widget
    return widget.render(name, data, attrs=attrs)
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/forms/widgets.py", line 360, in render
    options = self.render_options(choices, [value])
  File "/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/forms/widgets.py", line 376, in render_options
    for option_value, option_label in chain(self.choices, choices):
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/db/djangoforms.py", line 574, in _generate_choices
    for inst in self._query:
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2330, in next
    return self.__model_class.from_entity(self.__iterator.next())
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 1445, in from_entity
    return cls(None, _from_entity=entity, **entity_values)
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 973, in __init__
    prop.__set__(self, value)
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 617, in __set__
    value = self.validate(value)
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 3475, in validate
    raise BadValueError('Property %s must be a list' % self.name)
BadValueError: Property hourly_rate_after_date must be a list

**Comment by babybunny** [comment]
there are a bunch of records with hourly_rate_after_date as an empty value.

**Comment by babybunny** [comment]
I added this default value to the records that didnt have anything for hourly_rate_after_date: ["2016-01-01 0"]

that fixed it.
