### ISSUE TITLE
ROOMS priorities of items that need to be done p3

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#264]
Broken List overviews
- View a list of all Order Forms. 
- View a list of all Items.

**Comment by babybunny** [comment]
otrder forms fixed.

**Comment by babybunny** [comment]
https://rebuildingtogethercaptain.appspot.com/room/item

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation.402262285782287827/room/staff.py", line 53, in dispatch
    super(StaffHandler, self).dispatch(*a, **k)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation.402262285782287827/room/staff.py", line 447, in get
    return _EntryList(self.request, ndb_models.Item, 'item_list')
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation.402262285782287827/room/staff.py", line 225, in _EntryList
    return common.Respond(request, template, d)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation.402262285782287827/room/common.py", line 192, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation.402262285782287827/room/templates/item_list.html", line 1, in top-level template code
    {%extends "base.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation.402262285782287827/room/templates/base.html", line 55, in top-level template code
    {% block body %}Body Placeholder{% endblock %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation.402262285782287827/room/templates/item_list.html", line 46, in block "body"
    <img src="{{ webapp2.uri_for("ItemThumbnail", id=item.key.integer_id()) }}">
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1732, in uri_for
    return request.app.router.build(request, _name, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1247, in default_builder
    raise KeyError('Route named %r is not defined.' % name)
KeyError: "Route named 'ItemThumbnail' is not defined."

**Comment by babybunny** [comment]
fixed.
