### ISSUE TITLE
sites_and_captains timeout for 2017 Safe

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#276]
Just times out.   Chris brought this up. 

it takes 60 seconds!  
GET /room/sites_and_captains HTTP/1.1" 500

Log has a gnarly stack trace.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/staff.py", line 53, in dispatch
    super(StaffHandler, self).dispatch(*a, **k)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/staff.py", line 195, in get
    return common.Respond(self.request, 'site_list', d)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/common.py", line 192, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 891, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/templates/site_list.html", line 11, in root
    {% block breadcrumb %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/templates/base.html", line 59, in root
    </div>
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/templates/site_list.html", line 48, in block_body
    <span class="sortorder">{{ site.number }}</span>
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/jinja2-2.6/jinja2/runtime.py", line 180, in call
    return __obj(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/ndb_models.py", line 480, in BudgetStatement
    return '$%0.2f unspent budget' % self.BudgetRemaining()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/ndb_models.py", line 464, in BudgetRemaining
    return self.budget - self.Expenses()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/ndb_models.py", line 460, in Expenses
    self.VendorReceiptTotal())
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/ndb_models.py", line 446, in VendorReceiptTotal
    return sum(cr.amount or 0 for cr in self.VendorReceipts)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/ndb_models.py", line 446, in <genexpr>
    return sum(cr.amount or 0 for cr in self.VendorReceipts)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-workstation-blue.402233163833038454/room/ndb_models.py", line 34, in Items
    key=lambda o: o.modified, reverse=True):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1810, in next
    self._more_results) = self._fut.get_result()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 378, in check_success
    self.wait()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 362, in wait
    if not ev.run1():
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 268, in run1
    delay = self.run0()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 230, in run0
    callback(*args, **kwds)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 533, in _on_future_completion
    self._help_tasklet_along(ns, ds_conn, gen, val)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 439, in _help_tasklet_along
    datastore._SetConnection(save_ds_connection)
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.

**Comment by babybunny** [comment]
there are 161 sites.  some have tons of expenses.  too much to compute at list time.  will have to pre-compute the budget statement and store it on the site.

**Comment by babybunny** [comment]
I saved the expense value on the site, makes it faster to list the sites, slightly slower to save each one.
