### ISSUE TITLE
crash in sites_and_captains

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#281]
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/staff.py", line 53, in dispatch
    super(StaffHandler, self).dispatch(*a, **k)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/staff.py", line 197, in get
    return common.Respond(self.request, 'site_list', d)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/common.py", line 192, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/templates/site_list.html", line 1, in top-level template code
    {%extends "base.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/templates/base.html", line 55, in top-level template code
    {% block body %}Body Placeholder{% endblock %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/templates/site_list.html", line 74, in block "body"
    <br>{{ site.BudgetStatement() }}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/ndb_models.py", line 487, in BudgetStatement
    if self.BudgetRemaining() > 0:
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/ndb_models.py", line 472, in BudgetRemaining
    return self.budget - self.Expenses()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/ndb_models.py", line 467, in Expenses
    self.RecomputeExpenses()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/ndb_models.py", line 463, in RecomputeExpenses
    self.put()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/button2.402308418231614853/room/ndb_models.py", line 383, in put
    self.jurisdiction = self.jurisdiction_choice.get().name
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by babybunny** [comment]
looks like some bad data.  there is a site that doesn't have a jurisdiction_choice.

**Comment by babybunny** [comment]
There are records that look like the test data records. I don't know how they got added to the production system.  probably a misuse of remote_api, somehow.  

I had deleted the Jurisdiction "FunkyTown" earlier.  That's what created the error, because there were NewSite records that referred to that Jurisdiction by key. 

I deleted the 2 NewSite records that referred to it.  That fixed the site list page.  But now there are Orders and other expense types that are crashing their respective views.  

Time to clean up that erroneous test data I guess.

**Comment by babybunny** [comment]
the bad site has key 
**Key(NewSite, 5308625127997440)
**

**Comment by babybunny** [comment]
deleting stuff with site key 
ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchQLEgdOZXdTaXRlGICAgNiphbcJDA

**Comment by babybunny** [comment]
deleting supplier key
ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchULEghTdXBwbGllchiAgIC4kLmzCgw

and Item and OrderSheet

**Comment by babybunny** [comment]
there is not a lot of data left in program 2011 Test.  but all the views seem to work now.
