### ISSUE TITLE
Reporting Summary error

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#291]
https://rebuildingtogethercaptain.appspot.com/room/site_summary/5772013629079552

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-worstatation-blue.402466682951354435/room/staff.py", line 56, in dispatch
    super(StaffHandler, self).dispatch(*a, **k)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-worstatation-blue.402466682951354435/room/staff.py", line 149, in get
    return common.Respond(self.request, 'site_summary', {'site': site})
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-worstatation-blue.402466682951354435/room/common.py", line 192, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-worstatation-blue.402466682951354435/room/templates/site_summary.html", line 1, in top-level template code
    {%extends "base.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-worstatation-blue.402466682951354435/room/templates/base.html", line 55, in top-level template code
    {% block body %}Body Placeholder{% endblock %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/luke-worstatation-blue.402466682951354435/room/templates/site_summary.html", line 146, in block "body"
    {{ cr.payment_date.strftime("%b %d %Y") }}
UndefinedError: 'None' has no attribute 'strftime'

**Comment by caripang** [comment]
It appears this is working now as of 9/25/2017.
