### ISSUE TITLE
fix tests on sitebudgetexport

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#308]
luke-stones-macbook-pro:default babybunny$ nose2 test.test_staff.StatefulTestStaffWithProgramAuto
........................E...........
======================================================================
ERROR: testSiteBudgetExport (test.test_staff.StatefulTestStaffWithProgramAuto)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/babybunny/rebuildingtogethercaptain-hrd/default/test/test_staff.py", line 74, in aTest
    response = self._get(path)
  File "/Users/babybunny/rebuildingtogethercaptain-hrd/default/test/test_staff.py", line 64, in _get
    return app.get(path, headers={'x-rooms-dev-signin-email': 'rebuildingtogether.staff@gmail.com'})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/webtest/app.py", line 330, in get
    expect_errors=expect_errors)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/webtest/app.py", line 643, in do_request
    self._check_status(status, res)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/webtest/app.py", line 675, in _check_status
    res)
AppError: Bad response: 405 Method Not Allowed (not 200 OK or 3xx redirect for http://localhost/room/site_budget_export)
405 Method Not Allowed

The method GET is not allowed for this resource.

**Comment by babybunny** [comment]
I removed this method for the list of routes for the simple GET test.

**Comment by babybunny** [comment]
This might be a good one to start with.   There is some method to automatically create requests for all routes, but since it assumes GET requests, it doesn't work for the PUTs.  currently the PUTs are not tested. 

Task here is to create a test method that will handle PUTs and make it do the right routes.
