### ISSUE TITLE
"Add a New Site" error code showing up

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#329]
Tried adding a new site to 2017 Team Build and 2017 NRD, and get this error:

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue320.403899301925348647/room/staff.py", line 56, in dispatch
    super(StaffHandler, self).dispatch(*a, **k)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue320.403899301925348647/room/staff.py", line 330, in get
    return common.Respond(self.request, self.template_file, d)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue320.403899301925348647/room/common.py", line 192, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue320.403899301925348647/room/templates/site.html", line 1, in top-level template code
    {%extends "base.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue320.403899301925348647/room/templates/base.html", line 50, in top-level template code
    {% block about_this_page %}About This Page Placeholder{% endblock %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue320.403899301925348647/room/templates/site.html", line 13, in block "about_this_page"
    <a href="{{ webapp2.uri_for('SiteView', id=site.key.integer_id()) }}">Back to Site #{{site.number}}</a>
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 372, in getattr
    return getattr(obj, attribute)
UndefinedError: 'site' is undefined

**Comment by babybunny** [comment]
I see this, too.  Looking ...

**Comment by babybunny** [comment]
got it.  fix deployed.

**Comment by caripang** [comment]
thanks for fixing all these bugs so quickly!

**Comment by caripang** [comment]
FYI - I tried to add 17807SAB to 2017 Team Build - I would get a note saying it was "Saving" and then transported back to the staff home page.  When I search for 17807SAB, it is not one of the sites available...can you please confirm how we can make sure these new sites are indeed saved and accessible?
