### ISSUE TITLE
View a list of all Staff Time entries for 2017 Safe. 

### ISSUE THREAD

**Issue by gregbernard** [babybunny/rebuildingtogethercaptain#365]
This blows up with an internal server error.

  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue361.404546409576775343/room/templates/stafftime_table.html", line 28, in top-level template code
    {{ entity.position.get().position_name|escape }}
UndefinedError: 'None' has no attribute 'get'

**Comment by caripang** [comment]
This is helpful to get an overview of which projects staff/AmeriCorps have been working on, especially for overall reporting.

https://rebuildingtogethercaptain.appspot.com/room/stafftime_by_program

Results in: 

Internal Server Error

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/staff.py", line 57, in dispatch
    super(StaffHandler, self).dispatch(*a, **k)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/staff.py", line 449, in get
    params=params, query=query)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/staff.py", line 339, in _EntryList
    return common.Respond(request, template, d)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/common.py", line 197, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/templates/site_expense_list.html", line 1, in top-level template code
    {%extends "base.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/templates/base.html", line 56, in top-level template code
    {% block body %}Body Placeholder{% endblock %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/templates/site_expense_list.html", line 25, in block "body"
    {% include table_template %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue358.404569495965733922/room/templates/stafftime_table.html", line 28, in top-level template code
    {{ entity.position.get().position_name|escape }}
UndefinedError: 'None' has no attribute 'get'

**Comment by babybunny** [comment]
stafftime entity without a position.  yes, can reproduce.   will look in the datastore. 

there are a lot of stafftime entries without positions.  but they all seem to be in a "new" state.  So let me filter out that state.

**Comment by babybunny** [comment]
fixed.  this loads for me on 2017 Safe.
https://rebuildingtogethercaptain-hrd.appspot.com/room/stafftime_by_program
