### ISSUE TITLE
crash in /cru_api.sitecaptain_create

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#407]
Encountered unexpected error from ProtoRPC method implementation: BadValueError (Expected complete Key, got Key('Captain', None)) (/base/data/home/runtimes/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/wsgi/service.py:191)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/wsgi/service.py", line 181, in protorpc_service_app
    response = method(instance, request)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/remote.py", line 414, in invoke_remote_method
    response = method(service_instance, request)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue357.405403750462638012/room/cru_api.py", line 125, in mdl_create
    g2d(request, mdl)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue357.405403750462638012/room/protorpc_messages.py", line 921, in SiteCaptainMessageToModel
    mdl.captain = ndb.Key(ndb_models.Captain, msg.captain)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1400, in __set__
    self._set_value(entity, value)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1145, in _set_value
    value = self._do_validate(value)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1092, in _do_validate
    value = self._call_shallow_validation(value)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1284, in _call_shallow_validation
    return call(value)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1331, in call
    newvalue = method(self, value)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 2017, in _validate
    (value,))
BadValueError: Expected complete Key, got Key('Captain', None)

**Comment by babybunny** [comment]
also see issue 408, this is similar.  I think it's about the ability to submit the form without selecting a captain.

**Comment by babybunny** [comment]
added better checking on the server side, so error sent to the client is not as obscure.  still need to fix client side.

**Comment by kate-mills** [comment]
issue 408 should have fixed this.
A site captain should not get past validation until both the captain and type are selected.  

Here is a link to the validation function that checks for this: https://github.com/babybunny/rebuildingtogethercaptain/blob/service/gae/js/app/models/sitecaptain.js

**Comment by kate-mills** [comment]
There is a new error that appears that the validation does not catch. 

sitecaptain.js:79 Uncaught TypeError: Cannot read property 'label' of undefined

**Comment by babybunny** [comment]
This would happen if the captain id is not found in the list of options.
Could be
- captain id is  wrong somehow
- captain id is empty
- list of options has changed, for example if it's in the middle of a
refresh from server.
