### ISSUE TITLE
in-kind donations viewing internal server error

### ISSUE THREAD

**Issue by billyrtp** [babybunny/rebuildingtogethercaptain#487]
when I select to view an in-kind donation that has been entered it gives me an internal server error for some and not for others. See site 18017EPA

https://rebuildingtogethercaptain.appspot.com/room/site/view/5846007501815808/

**Comment by andy-d** [comment]
Hi Billy,
Thanks! Yes for the second listed in-kind I see this as well. Here is a direct link that should reproduce and the stack trace

https://rebuildingtogethercaptain.appspot.com/room/inkinddonation_view/5891997004988416?site_id=5846007501815808

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/staff.py", line 102, in dispatch
    super(StaffOrCaptainHandler, self).dispatch(*a, **k)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/staff.py", line 626, in get
    {'entity': entity}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/common.py", line 193, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/inkinddonation_view.html", line 1, in top-level template code
    {%extends "base.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/base.html", line 78, in top-level template code
    {% block body %}Body Placeholder{% endblock %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/inkinddonation_view.html", line 6, in block "body"
    {%include "inkinddonation_static.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/inkinddonation_static.html", line 86, in top-level template code
    ${{ "%0.2f" % entity.materials_amount }}
TypeError: float argument required, not NoneType

**Comment by billyrtp** [comment]
Thanks Andy! Do we know when this might be resolved? I am hoping to view
and print in-kind records for NRD.


Billy Hoover | Operations & Impact Manager



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

**Comment by andy-d** [comment]
Hi Billy,
Let me take a look late today. I haven't been working in this area of the
code exactly but given the simple repro I expect a fix will be pretty
straightforward.
Andy

**Comment by billyrtp** [comment]
That would be awesome Andy! Thanks for giving this a look.


Billy Hoover | Operations & Impact Manager



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

**Comment by andy-d** [comment]
Hi Billy,
I've tracked the issue down to the fact that the "Materials Value" field for this in-kind donation was empty, instead of a numerical value. In order to work around the issue I have inputted $0 for now as the materials value, which you can feel free to update as necessary of course. As there's a workaround now would you mind if we drop the Priority-High label for now? Ping for @caripang as well on this question.

I going to hand this off to Luke in the meantime as he will have the best context on how to be more permissive about unexpected data.
Andy

**Comment by billyrtp** [comment]
Thanks Andy! That will help with the task and I can let our staff who need
that feature what the workaround is until it allows for an empty value.


Billy Hoover | Operations & Impact Manager



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*
