### ISSUE TITLE
Data corruption issue for 18804SSF

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#489]
https://rebuildingtogethercaptain.appspot.com/room/site/lookup/18804SSF

My apologies - I kept getting errors trying to create a new site, so I was trying to figure out which field was the issue, and now it seems I have multiple sites, but I can't find a way to delete the multiple sites on my own and find the one new site (18804SSF) so that we can start tracking it.

Data corruption issue, more than one site with number 18804SSF

**Comment by caripang** [comment]
FYI - it looks like there are still issues in saving sites.  "Internal Server Error" message when we tried to create a new site.

**Comment by caripang** [comment]
I think this is all related, but it seems now like we are also having issues viewing things that have been submitted:
https://rebuildingtogethercaptain.appspot.com/room/inkinddonation_view/5876693331869696?site_id=5781189172396032

Internal Server Error
The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/staff.py", line 102, in dispatch
    super(StaffOrCaptainHandler, self).dispatch(*a, **k)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/staff.py", line 626, in get
    {'entity': entity}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/common.py", line 193, in Respond
    request_handler.response.out.write(template.render(params))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/573c2cae20d3e94a/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/inkinddonation_view.html", line 1, in top-level template code
    {%extends "base.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/base.html", line 78, in top-level template code
    {% block body %}Body Placeholder{% endblock %}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/inkinddonation_view.html", line 6, in block "body"
    {%include "inkinddonation_static.html"%}
  File "/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue476.409113615339423199/room/templates/inkinddonation_static.html", line 78, in top-level template code
    ${{ "%0.2f" % entity.labor_amount }}
TypeError: float argument required, not NoneType

**Comment by babybunny** [comment]
the issue about viewing things that have been submitted - that seems to be resolved. 

I can still see the issue where it says "Data corruption issue, more than one site with number 18804SSF"
at https://rebuildingtogethercaptain.appspot.com/room/site/lookup/18804SSF

**Comment by babybunny** [comment]
I see three sites with that number. 18804SSF

there is only one that has a value for latest_computes_expenses.  id=5899977691758592

the others I will delete. 
id=5834918064029696
id=5797306800537600

no SiteCaptains for 5797306800537600  5834918064029696
no Orders for 5797306800537600  5834918064029696
(assume no other expense types because the expense total was empty)
no StaffTime for 5797306800537600  5834918064029696

that's all the reference types.  so I think we're good.

**Comment by babybunny** [comment]
now this site works. 
18804SSF
