### ISSUE TITLE
error in logs for staffposition

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#517]
GET rebuildingtogethercaptain.appspot.com/room/staffposition/5904231177388032

TypeError: this constructor takes no arguments

Looks like an error in the configuration of the router? 

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1101, in __call__
    handler = self.handler(request, response)
TypeError: this constructor takes no arguments

**Comment by babybunny** [comment]
This will be fixed once issue 455 is done. 

The root cause is in staff.py we have an incomplete handler. 
class StaffPosition():
  pass
