### ISSUE TITLE
ndb_models test failure throws noisy error

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#541]
======================================================================
ERROR: testProgram (test.test_cru_api.BugsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/babybunny/rebuildingtogethercaptain-hrd/default/test/test_cru_api.py", line 148, in tearDown
    test_models.DeleteAll(self.keys)
  File "/Users/babybunny/rebuildingtogethercaptain-hrd/default/test/test_models.py", line 578, in DeleteAll
    key.delete()
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/key.py", line 598, in delete
    return self.delete_async(**ctx_options).get_result()
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 378, in check_success
    self.wait()
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 362, in wait
    if not ev.run1():
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/eventloop.py", line 268, in run1
    delay = self.run0()
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/eventloop.py", line 230, in run0
    callback(*args, **kwds)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 530, in _on_future_completion
    exc=exc, tb=future.get_traceback())
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 469, in _help_tasklet_along
    self.set_exception(err, tb)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 341, in set_exception
    callback(*args, **kwds)
  File "/Users/babybunny/rebuildingtogethercaptain-hrd/default/gae/room/ndb_models.py", line 154, in _post_delete_hook
    cls.delete_by_model_key_id(key.id())
  File "/Users/babybunny/rebuildingtogethercaptain-hrd/default/gae/room/ndb_models.py", line 150, in delete_by_model_key_id
    index.delete(document_ids=map(lambda d: d.doc_id, index.search("model_key_id={}".format(model_key_id))))
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_rpc.py", line 105, in positional_wrapper
    return wrapped(*args, **kwds)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/api/search/search.py", line 3896, in search
    return self.search_async(query, deadline=deadline, **kwargs).get_result()
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_rpc.py", line 105, in positional_wrapper
    return wrapped(*args, **kwds)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/api/search/search.py", line 3915, in search_async
    return _RpcOperationFuture('Search', request, response, deadline, hook)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/api/search/search.py", line 273, in __init__
    self._rpc = apiproxy_stub_map.UserRPC('search', deadline=deadline)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 416, in __init__
    self.__rpc = CreateRPC(service, stubmap)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 70, in CreateRPC
    assert stub, 'No api proxy found for service "%s"' % service
AssertionError: No api proxy found for service "search"

**Comment by babybunny** [comment]
test_models sets up a bunch of models using 
from google.appengine.ext import testbed

This also sets up a stub for search.  when a test fails, the cleanup tries to delete all the models, and it tries to hit the search API but the stub is not available at that time.  

probably something about tearing down the stubs being done in the wrong order.

**Comment by babybunny** [comment]
possibly because nobody is calling tb.deactivate() ?

**Comment by babybunny** [comment]
this might be a nosegae thing.   the nosegae module doesn't appear to know about search or memcache stubs.  it exists to help get the environment set up for when you're using nose to run tests (which we are).   

actually we are using nose2 and the relevant module is https://github.com/udacity/nose2-gae

the memcache stub throws a similar error.

this could be hard to fix, and low value.  the spurious error is not a big deal.
