### ISSUE TITLE
dev server doesn't initialize cleanly

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#543]
main symptom is that the datastore is empty, and nobody can log in to an account.  there's a race around initializing service stubs I think.  adding a retry should work.

$ ./dev_server.sh 
INFO     2020-06-01 05:24:27,895 stub_util.py:382] Applying all pending transactions and saving the datastore
INFO     2020-06-01 05:24:27,896 stub_util.py:385] Saving search indexes

Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update

INFO     2020-06-01 05:24:34,539 devappserver2.py:232] Using Cloud Datastore Emulator.
We are gradually rolling out the emulator as the default datastore implementation of dev_appserver.
If broken, you can temporarily disable it by --support_datastore_emulator=False
Read the documentation: https://cloud.google.com/appengine/docs/standard/python/tools/migrate-cloud-datastore-emulator
Help us validate that the feature is ready by taking this survey: https://goo.gl/forms/UArIcs8K9CUSCm733
Report issues at: https://issuetracker.google.com/issues/new?component=187272

INFO     2020-06-01 05:24:34,650 devappserver2.py:289] Skipping SDK update check.
INFO     2020-06-01 05:24:35,145 datastore_emulator.py:155] Starting Cloud Datastore emulator at: http://localhost:21221
Traceback (most recent call last):
  File "dev_utilities.py", line 42, in <module>
    init_stubs_and_models()
  File "dev_utilities.py", line 34, in init_stubs_and_models
    secure=False)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 1137, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 842, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "/Users/babybunny/google-cloud-sdk/platform/google_appengine/google/appengine/tools/appengine_rpc.py", line 486, in Send
    f = self.opener.open(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 61] Connection refused>

**Comment by babybunny** [comment]
when it's working correctly you'll know because it prints 
INFO     2020-05-31 22:35:17,075 ndb_models.py] Recomputing expenses for 110TEST
INFO     2020-05-31 22:35:17,933 ndb_models.py] Recomputing expenses for 110TEST
....

**Comment by babybunny** [comment]
pushed a fix
